version: '3'
services:
  web:
      restart: always
      build: 
        context: .
        dockerfile: Dockerfile
      image: "consul.webapi.servicea"
      container_name: "consul.webapi.servicea"
      ports:
        - "9001:9001"